config/routes.rb
require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  username == 'admin' && password == 'qwerty'
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/async/tasks'

  # Base
  root to: 'welcome#islands'
  get '/index' => 'welcome#index'
  get '/page_404' => 'welcome#page_404', as: :page_404

  get '/articles' => 'welcome#legacy_articles'
  get '/search'   => 'welcome#legacy_search'

  get '/new',  to: redirect('/', status: 301) # 410
  get '/news', to: redirect('/', status: 301)

  get '/authors_articles', to: redirect('/', status: 301)
  get '/blogs.rss', to: redirect('/rss.rss',  status: 301)
  get '/archive',   to: redirect('/archive_numbers', status: 301)
  get '/archives',  to: redirect('/archive_numbers', status: 301)
  get '/partners',  to: redirect('/pages/partners',  status: 301)

  get '/hubs/future', to: redirect('/hubs/future-future', status: 301)

  get '/materia',  to: redirect('http://artelectronics.ru/posts/myslyaschaya-materiya', status: 301)
  get '/materiya', to: redirect('http://artelectronics.ru/posts/myslyaschaya-materiya', status: 301)

  # XML feeds
  get '/feedly.rss'        => 'welcome#feedly',      defaults: { format: :rss }
  get '/novoteka.rss'      => 'welcome#novoteka',      defaults: { format: :rss }
  get '/yandex.rss'        => 'welcome#yandex',        defaults: { format: :rss }
  get '/rss.rss'           => 'welcome#rss',           defaults: { format: :rss }
  get '/rss_full.rss'      => 'welcome#rss_full',      defaults: { format: :rss }
  get '/telegraf_full.rss' => 'welcome#telegraf_full', defaults: { format: :rss }
  get '/rambler.rss'       => 'welcome#rambler',       defaults: { format: :rss }
  get '/surfingbird.rss'   => 'welcome#surfingbird',   defaults: { format: :rss }

  get '/flipboard_culture.rss' => 'welcome#flipboard_culture', defaults: { format: :rss }
  get '/flipboard_tech.rss'    => 'welcome#flipboard_tech',    defaults: { format: :rss }

  get '/sitemap.xml'       => 'welcome#sitemap',       defaults: { format: :xml }

  # Login system
  devise_for :users, path: '',
    :path_names => {
      sign_in:  'login',
      sign_up:  'signup',
      sign_out: 'logout'
    },
    :controllers => {
      :omniauth_callbacks => "omniauth_callbacks",
      :confirmations      => "confirmations",
      :registrations      => "registrations",
      :sessions           => "sessions",
      :passwords          => "passwords"
    }

  devise_scope :user do
    get '/account_should_be_activate' => 'registrations#account_should_be_activate'
  end

  # Personal
  get "cabinet" => "users#cabinet", as: :cabinet

  # Search
  match "search/:squery" => "search#index", via: %w[ get post ], as: :qsearch

  # Special Posts
  post '/tatlin_postcard' => 'special_posts#tatlin_postcard'

  %w[ authors archive_numbers ].each do |model|
    resources model do
      collection do
        get :manage
      end
    end
  end

  get '/authors/:id' => 'authors#show', constraints: {:id => /[^\/]+/}
  get "authors/by/:letter" => "authors#by_letter", as: :author_by_letter

  resources :meta_data

  TheAudit::Routes.mixin(self)
  TheBanners::Routes.mixin(self)

  # Subscribers
  post "subscribers/add" => "subscribers#add", as: :add_subscriber

  namespace :admin do
    TheRole::Routes.mixin(self)
  end

  # TheComments
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]

  concern :sortable_tree do
    collection do
      get  :manage
      post :rebuild
    end
  end

  # legacy url
  get '/blogs/:id' => 'welcome#legacy_blog', constraints: { id: /\d{1,3}/ }

  # Direct routes
  %w{ hubs pages posts blogs }.each do |name|
    resources name, concerns: :sortable_tree do
      get :print

      member do
        patch  :main_image_crop_270x210
        patch  :main_image_crop_100x100
        patch  :main_image_rotate
        delete :main_image_delete
      end
    end
  end

  resources :hubs do
    post :expand_node, on: :collection
  end

  # Users
  resources :users, only: %w[ edit update ] do
    patch  :change_email
    patch  :change_password

    patch  :avatar_crop
    delete :avatar_delete

    %w[ hubs pages posts blogs ].each do |name|
      resources name, concerns: :sortable_tree do
        get :my, on: :collection
      end
    end
  end

  # tags
  # tags
  get "tag/:tag" => "tags#show", as: :tag

  # /users/:user_id/manage/posts
  get "manage/:pub_type" => 'posts#manage', as: :pubs_manage
  get "users/:user_id/manage/:pub_type" => 'posts#manage', as: :user_pubs_manage
  get "/:id" => 'hubs#system_section', as: :system_hub

  # Mailer
  get '/rails/mailers' => "rails/mailers#index"
  get '/rails/mailers/*path' => "rails/mailers#preview"

  # Legacy Urls
  get '/:c_slug/:s_slug/:id' => 'welcome#legacy_post'
  get '/:c_slug/:s_slug'     => 'welcome#legacy_hub'
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable_on :names, :words, :titles
  include BasePublication
  include FutureTextMethods

  # relations
  has_many :authorships
  has_many :authors, through: :authorships

  def inline_author_tags
    authors.pluck(:name).join(', ')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PublicationController

  def index
    super
    render template: 'publications/index'
  end

  def show
    super
    render template: 'publications/show'
  end

  def edit
    @authors = Author.pluck(:name)

    super
  end

  def update
    authors = Author.where(name: params[:post][:author_list].split(',').map { |name| name.strip } )
    @pub.authors = Array.wrap(authors)

    super
  end

  private

  def set_post_and_user
    @post = @klass.publication_access(current_user).with_users.friendly_first(params[:id])

    # Hook for fix lagacy urls
    if @post.blank?
      blog = Blog.publication_access(current_user).with_users.friendly_first(params[:id])
      return redirect_to(blog, status: 301) if blog
    end

    return page_404 unless @post

    @user = @post.user
    @owner_check_object = @post
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def tags_to_str post
    raw tags_to_ary( post ).join ', '
  end

  def tags_to_ary post
    AppConfig.tag_contexts.inject([]){ |o, v| o += tag_inline_links( post, v )}
  end
  
  def tags_by_context post, context
    raw tag_inline_links( post, context ).join ', '
  end

  # private

  def tag_inline_links post, context
    post.send( "inline_#{ context }_tags" ).split(', ').map do |tag|
      link_to tag, tag_url(tag)
    end
  end
end

app/views/art_electronics/posts/_form.html.haml
- content_for :editor do
  %script 
    var CKEDITOR_BASEPATH = "/javascripts/ckeditor/";

  = javascript_include_tag "ckeditor/ckeditor"
  = javascript_include_tag "vendors/ckeditor/init"
  
= render partial: 'shared/crop_image_form', locals: { object: @post }

= form_for @post, html: { enctype: "multipart/form-data", role: :form } do |f|
  = render partial: 'the_notification/form', locals: { object: @post, format: :html }

  = hidden_field_tag 'post_id',    @post.id
  = hidden_field_tag 'post_klass', @post.class

  = render partial: 'shared/main_image_toolbar', locals: { f: f, object: @post }
  
  .form-group
    = f.label :title, t('pubs.title')
    = f.text_field :title, class: 'form-control'

  = render partial: "shared/top_fields", locals: { f: f, object: @post, selector_hubs: @selector_hubs }

  .form-group
    = f.label :raw_intro, t('pubs.intro')
    = f.text_area :raw_intro, class: :redactor_intro
  
  .form-group
    = f.label :raw_content, t('pubs.content')
    = f.text_area :raw_content, class: :redactor_content
  
  .form-group#tags{ data: { contexts: AppConfig.tag_contexts } }
    = label_tag 'tags', t('posts.tags.title')
    = render partial: 'tag_fields', locals: { post: @post }

  - if !@post.new_record?
    .form-group
      - options = options_for_select(publication_states, @post.state)
      .row
        .col-md-12= f.label :state, t('pubs.state')
      .row
        .col-md-5= f.select :state, options, {}, class: 'form-control input-medium'
  
  .form-group
    = f.submit t('pubs.save'), class: 'btn btn-info'

  = render partial: 'shared/pub_stats', locals: { object: @post }

app/views/art_electronics/posts/_informer.html.haml
%b= t 'posts.author'
= link_to post.user.login, user_path(post.user.login)

- if post.published_at
  %b= t 'posts.published_at'
  = post.published_at.strftime('%d.%m.%Y')

%b= t 'posts.views'
= post.show_count

- if post.respond_to? :comments
  %b= t 'posts.comments'
  = link_to post.comments_sum, show_url(post, :comments)

app/views/art_electronics/posts/_links_to_attachments.html.haml
- content_for :swf_viewer do
  = render partial: 'viewer'

.panel.panel-default
  .panel-body
    .post_versions_links
      %table
        %tr
          %td
            - if @post.has_future_text?
              = link_to t('.flash_version'), '#', class: :flash_version
          %td
            - if @post.has_pdf?
              = link_to t('.pdf_version'), @post.pdf_file, class: :pdf_version, rel: :nofollow

- if @post.has_future_text? || @post.has_pdf?
  %p
    - if @post.has_future_text?
      = link_to "future test", @post.future_text
    - if @post.has_pdf?
      = link_to "pdf test", @post.pdf_file

app/views/art_electronics/posts/_read_more.html.haml
%p.read_more  
  - if !post.content.blank?
    = link_to raw(t 'posts.read_more'), show_url(post)
  - else
    = link_to raw(t 'posts.to_comments'), show_url(post, :comments)

app/views/art_electronics/posts/_tag_by_context.html.haml
.tags
  %b= t 'posts.tags.context.word' 
  = tags_by_context post, 'word'
.tags
  %b= t 'posts.tags.context.name' 
  = tags_by_context post, 'name'
.tags
  %b= t 'posts.tags.context.title'  
  = tags_by_context post, 'title'

app/views/art_electronics/posts/_tag_fields.html.haml
.panel.panel-default
  .panel-body
    - AppConfig.tag_contexts.each do | c |
      .form-group
        - id = "post[#{ c }_list]"
        = label_tag id, t(".context.#{ c }")
        = text_field_tag id, post.send("inline_#{ c }_tags") , 'data-tags' => @tags[ c ].to_json

app/views/art_electronics/posts/_viewer.html.haml
.viewer_block.hide_block{ data: { 'swf-url' => "#{@post.future_text}", 'swf-type' => @post.get_future_type } }
  .hide_viewer
    .bg
    = link_to t('.close'), '#', class: 'viewer_close_message'
  #viewer

app/views/art_electronics/posts/edit.html.haml
- content_for :express_nav do
  %p= link_to t('app.cabinet'), cabinet_url
  %p= link_to t('posts.show'), url_for(@post)
  %p= link_to t('posts.list'), url_for([:manage, :posts])

%h1= t "posts.edit"

= render 'posts/form'

= render partial: 'the_storages/form', locals: { storage: @post }
= render partial: 'the_storages/list', locals: { storage: @post }

app/views/art_electronics/posts/index.html.haml
- content_for :hubs_widget do
  = render partial: 'layouts/widgets/hubs'

/ - content_for :sub_hubs_widget do
/   = render partial: 'layouts/widgets/sub_hubs'

- content_for :recent_comments_widget do
  = render partial: 'layouts/widgets/recent_comments'

- content_for :tag_search_widget do
  = render partial: 'layouts/widgets/tag_search'

= paginate @posts

- @posts.each do |post|
  .panel.panel-success
    .panel-heading
      %h3
        = link_to post.title, show_url(post)
        (#{ post.state })
    .panel-body
      %p
        - if post.main_image?
          = link_to show_url(post) do
            %span{ style: "float: left; margin: 0 10px 10px 0;" }= image_tag post.main_image.url(:preview), class: :preview

        = raw post.intro
      = render partial: "posts/read_more", locals: { post: post }

    .panel-footer
      .tags= tags_to_str( post )
      = render partial: "posts/informer", locals: { post: post }

= paginate @posts

app/views/art_electronics/posts/manage.html.haml
= render partial: "shared/per_page"

%p= link_to t('posts.new'), url_for([:new, model_name])

%ol.sortable_tree{ data: { max_levels: 5, rebuild_url: url_for([:rebuild, controller_name]) } }
  = sortable_tree @posts

= paginate @posts

app/views/art_electronics/posts/new.html.haml
- content_for :express_nav do
  %p= link_to t('app.cabinet'), cabinet_url
  %p= link_to t('posts.manage'), url_for([:manage, @post])

%h1= t 'posts.new'

- if @selector_hubs.blank?
  = t 'hubs.have_not_available_hubs'
- else
  = render 'posts/form'

app/views/art_electronics/posts/show.html.haml
- content_for :hubs_widget do
  = render partial: 'layouts/widgets/hubs'

/ - content_for :sub_hubs_widget do
/   = render partial: 'layouts/widgets/sub_hubs'

- content_for :recent_comments_widget do
  = render partial: 'layouts/widgets/recent_comments'

- content_for :tags_widget do
  = render partial: 'layouts/widgets/tags', locals: { post: @post }

.panel.panel-success
  .panel-heading
    %h3
      = @post.title
      (#{ @post.state })
  .panel-body
    - if @post.has_future_text?
      = render partial: "posts/links_to_attachments"

    - if @post.main_image?
      %p= image_tag @post.main_image.url(:preview), class: :preview
    %p= raw @post.intro

    %p= raw @post.content
  
  .panel-footer
    .authors
      %b Авторы
      - @post.authors.each do |author|
        = link_to author.name, author
    
    = render partial: 'posts/tag_by_context', locals: { post: @post }
    
    = render partial: "posts/informer", locals: { post: @post }

= render partial: "the_comments/tree", locals: { commentable: @post, comments_tree: @comments }